### ISSUE TITLE
Change recheck time for live

### ISSUE THREAD

**Issue by mrjoedawg** [Michele0303/tiktok-live-recorder#105]
Hey, I was wondering if it is possible to decrease the "recheck time" for live from 5 mins to 1 min or something?

**Comment by jgore077** [comment]
@mrjoedawg Are you still looking for a fix because I can help you

**Comment by Rustbeard86** [comment]
https://github.com/Michele0303/tiktok-live-recorder/issues/93#issuecomment-2243908277
