### ISSUE TITLE
HTTP error 404 not found

### ISSUE THREAD

**Issue by mrjoedawg** [Michele0303/tiktok-live-recorder#106]
Hey this program worked for me until today, now I get this errors all the time: 

[https @ 000001d69baa0580] HTTP error 404 Not Found
[in#0 @ 000001d69ba9e340] Error opening input: Server returned 404 Not Found
Error opening input file https://pull-f5-tt02.fcdn.eu.tiktokcdn.com/stage/stream-3861657808571728834_or4.flv?expire=1709820369&session_id=147-202402221406081A7EC385038C2F178E54&sign=3b61ee8e05564281af5044a76330a547.
Error opening input files: Server returned 404 Not Found

I have tried to reinstall and nothing seems to work sadly.

**Comment by Michele0303** [comment]
Change your ip

**Comment by mrjoedawg** [comment]
Thanks for the answer, so you mean by using a VPN for example or how do I change IP?

**Comment by iSuckAtCoding8** [comment]
Did you ever manage to resolve this? I'm now having the same problem when I didn't before. This happens on lives that have not ended.
