### ISSUE TITLE
cannot get it to recognize I have ffmpeg installed

### ISSUE THREAD

**Issue by aaronauthor** [Michele0303/tiktok-live-recorder#107]
"$ python main.py -user ************ -mode automatic -output /c/Users/*****/Videos/tiktok-lives -ffmpeg --auto-convert
[*] 2024-02-25 22:32:00 - INFO - USERNAME: ********
[*] 2024-02-25 22:32:00 - INFO - ROOM_ID:  **************
[*] 2024-02-25 22:32:05 - INFO - LIVE URL: super long url
[*] 2024-02-25 22:32:05 - INFO - STARTED RECORDING...
[*] 2024-02-25 22:32:05 - INFO - [PRESS 'q' TO STOP RECORDING]
[*] 2024-02-25 22:32:05 - ERROR - FFmpeg is not installed"

and then

"$ pip install FFmpeg
Requirement already satisfied: FFmpeg in c:\users\*****\appdata\local\programs\python\python310\lib\site-packages (1.4)"

**Comment by Michele0303** [comment]
Run:

```
pip uninstall ffmpeg
pip install ffmpeg-python
```
