### ISSUE TITLE
After i stopped the recording manually, file is unusable

### ISSUE THREAD

**Issue by CyberbobGR** [Michele0303/TikTok-Live-Recorder#11]
I pressed ctrl+c and waited as the instructions said.

> [out#0/mp4 @ 0000021ce2fdbec0] Error writing trailer: Immediate exit requestedts/s speed=   1x
frame=137930 fps= 30 q=-1.0 Lsize=   97792kB time=01:16:37.97 bitrate= 174.2kbits/s speed=   1x
video:62025kB audio:35922kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exiting normally, received signal 2.

> ERROR: Interrupted by user
> Traceback (most recent call last):
>   File "C:\TikTok-Live-Recorder\main.py", line 67, in <module>
>     main()
>   File "C:\TikTok-Live-Recorder\main.py", line 61, in main
>     bot.run()
>   File "C:\TikTok-Live-Recorder\tiktokbot.py", line 45, in run
>     self.start_recording()
>   File "C:\TikTok-Live-Recorder\tiktokbot.py", line 55, in start_recording
>     os.system(f"youtube-dl --hls-prefer-ffmpeg --no-continue --no-part -o {output} {live_url}")
> KeyboardInterrupt
> ^C

The file that was generated can not be played.

**Comment by Michele0303** [comment]
Try with vlc
https://www.videolan.org/vlc/

**Comment by CyberbobGR** [comment]
> Try with vlc https://www.videolan.org/vlc/

Tried, same results, video can't be played.

**Comment by Michele0303** [comment]
https://github.com/Michele0303/TikTok-Live-Recorder/releases/tag/2.3
