### ISSUE TITLE
Exception caught in main: [-] Unable to find stream url.

### ISSUE THREAD

**Issue by Kirk75it** [Michele0303/tiktok-live-recorder#112]
Why do I often get this error, both when using room_id and when using user?

 2024-03-11 09:45:22 - INFO - Testing http://127.0.0.1:9666...
[*] 2024-03-11 09:45:23 - INFO - Proxy set up successfully
[*] 2024-03-11 09:45:25 - INFO - USERNAME: **********************
[*] 2024-03-11 09:45:25 - INFO - ROOM_ID:  ***********************
[*] 2024-03-11 09:45:30 - ERROR - 'stream_url'
[*] 2024-03-11 09:45:30 - ERROR - Exception caught in main:
[-] Unable to find stream url.

V. 4.1

**Comment by OperationJosef** [comment]
Happens to me aswell ganz is this Software
