### ISSUE TITLE
Recheck user in one minute

### ISSUE THREAD

**Issue by DraganVictor14** [Michele0303/tiktok-live-recorder#114]
Hello, as you know if I automatically choose when to record the live, each attempt is every 5 minutes, correct! Unfortunately, I missed a live of about 5 minutes, during which it did not record at all! The question is how to recheck once  in a minute?

**Comment by sotero1113** [comment]
Update the AUTOMATIC_MODE variable in the enums.py file to 1 instead of 5. Rechecking so many times might get your IP block so you might want to use a proxy IP address

**Comment by Kiges** [comment]
> Update the AUTOMATIC_MODE variable in the enums.py file to 1 instead of 5. Rechecking so many times might get your IP block so you might want to use a proxy IP address

Hey, what's the reason behind using an enum int? why not just use .env variables? Maybe just setting seconds could be more standard-related.

**Comment by Naderrnawar** [comment]
> Update the AUTOMATIC_MODE variable in the enums.py file to 1 instead of 5. Rechecking so many times might get your IP block so you might want to use a proxy IP address

How to do that?

**Comment by Michele0303** [comment]
> > Aggiorna la variabile AUTOMATIC_MODE nel file enums.py a 1 invece che a 5. Ricontrollando così tante volte potresti ottenere il blocco IP, quindi potresti voler usare un indirizzo IP proxy
> 
> Come fare?

open enums.py file and edit this line:

![image](https://github.com/user-attachments/assets/eefda532-aeee-4e4a-a557-ada59be48cb0)


(It is likely that you will be blocked by TikTok.)
