### ISSUE TITLE
Cannot use automatic mode

### ISSUE THREAD

**Issue by Incym** [Michele0303/tiktok-live-recorder#115]
There is no problem with manual recording, but there is this error in automatic mode:
 Exception caught in main:
module 'ffmpeg' has no attribute 'Error'
![image](https://github.com/Michele0303/tiktok-live-recorder/assets/96464798/30e16a6e-43f2-4afc-a22b-3e101264e924)

**Comment by ithotline** [comment]
I'm getting same error. Both in windows and kali.

**Comment by Michele0303** [comment]
Fixed in version 5.4
