### ISSUE TITLE
Error Stream URL

### ISSUE THREAD

**Issue by jean75000** [Michele0303/tiktok-live-recorder#118]
Hello,

thanks for your contributions !!!

Can you fix this error ?: 

![1](https://github.com/Michele0303/tiktok-live-recorder/assets/168682836/ec45fa8e-bdaa-4129-9032-ca7ec26c2566)

I have sometimes this error and the script stop i must relaunch the script

Thanks

Have a nice day

**Comment by Michele0303** [comment]
**NEW VERSION RELEASED:**

https://github.com/Michele0303/tiktok-live-recorder/releases/tag/5.0
