### ISSUE TITLE
The script no longer works

### ISSUE THREAD

**Issue by jean75000** [Michele0303/tiktok-live-recorder#120]
Hello,

the script no longer works today, Tiktok has modified its code.
To retrieve the Roomid, the person must first be connected live and we can then retrieve it on their profile page.

without a connected account, it would be necessary to check that the user is live and then retrieve their roomid from the user's profile page.

Sincerely

**Comment by Michele0303** [comment]
I'm developing a new version

**Comment by jean75000** [comment]
you are the best:)

**Comment by jean75000** [comment]
I would be happy to be a beta tester, if you want.

**Comment by jean75000** [comment]
the script works again tiktok had to correct its code, thank you for your responsiveness for the ticket that I opened

**Comment by Eikreis** [comment]
So as to not create a bunch of duplicate issues, it seems the script is down again possibly due to tiktok changing it's code again. Room_id not found on everyone, whether recording by user or room_id, both in automatic mode and when I know someone is live. 

Looking forward to the new version!

**Comment by jean75000** [comment]
yes unfortunately the script no longer works again :(

**Comment by Michele0303** [comment]
As soon as I have some time I will fix it

**Comment by DraganVictor14** [comment]
I can't confirm that the app is no longer works for me!
I have a question for developer!Do you developed a method to send recorded files directly to telegram?

**Comment by gkarmas** [comment]
> As soon as I have some time I will fix it

yes please. Standing by🤞

**Comment by Michele0303** [comment]
> I can't confirm that the app is no longer works for me!
> I have a question for developer!Do you developed a method to send recorded files directly to telegram?

I will implement it in the future

**Comment by gkarmas** [comment]
By the way, it still works by using room id, but doesn't work by using username as of 5-6 hours ago.

**Comment by Michele0303** [comment]
**NEW VERSION RELEASED:**

https://github.com/Michele0303/tiktok-live-recorder/releases/tag/5.0
