### ISSUE TITLE
why i cant record in android

### ISSUE THREAD

**Issue by FaerieKnight** [Michele0303/tiktok-live-recorder#121]
It said that room id not found and try again in 2 min (it is loop btw)

**Comment by DraganVictor14** [comment]
I used last week a VPN app to fix but I with VPN actived doesn't works anymore

**Comment by Kaimeera** [comment]
Update to the new version and try. I think it's an issue with TT too bc even when I try to manually enter room_ID, it doesn't show on the page source.

**Comment by sotero1113** [comment]
> Update to the new version and try. I think it's an issue with TT too bc even when I try to manually enter room_ID, it doesn't show on the page source.

its roomId now, try: `re.findall(r"\"roomId\":\"(.*?)\"", content) `

and for user try: `re.findall(r"\"uniqueId\":\"(.*?)\"", content)`

**Comment by Michele0303** [comment]
Try new version
