### ISSUE TITLE
Where do You find Roomid?

### ISSUE THREAD

**Issue by AxelZable** [Michele0303/tiktok-live-recorder#122]
Hello,

Sorry I am looking for the roomid is it the @username of each account. I use it but I get the error Username/Room_id not found or the user has never been in live.
I need help please....

**Comment by Michele0303** [comment]
Try:

https://github.com/Michele0303/tiktok-live-recorder/releases/tag/4.1.1

**Comment by Michele0303** [comment]
**NEW VERSION RELEASED:**

https://github.com/Michele0303/tiktok-live-recorder/releases/tag/5.0
