### ISSUE TITLE
Where can I donate to help you fix this?

### ISSUE THREAD

**Issue by blankonxkonde** [Michele0303/tiktok-live-recorder#123]
I have an error. It seems like anyone else where I cannot end the recording when I press 'q' or when the live is ended

**Comment by richiec77** [comment]
Hey Liam.
Out of interest which project do you use now?

**Comment by Michele0303** [comment]
**NEW VERSION RELEASED:**

https://github.com/Michele0303/tiktok-live-recorder/releases/tag/5.0
