### ISSUE TITLE
still cant find room_id anyone else?

### ISSUE THREAD

**Issue by mani2200** [Michele0303/tiktok-live-recorder#126]

**Comment by Elicard** [comment]
Yes I'm getting every error in the book it seems man, let's just give it some time I'm sure it will be fixed soon

**Comment by iSuckAtCoding8** [comment]
Not working reliably for me on 4.1.1. Some people say if you use room id instead of username, it works well but not sure where to get that from.

**Comment by Elicard** [comment]
> Not working reliably for me on 4.1.1. Some people say if you use room id instead of username, it works well but not sure where to get that from.

I have managed to find the room_id in the console but i still only got the recordings to work some of the time

**Comment by victor00000** [comment]
updated to 4.1.1 still cannot find roomId from user name.

**Comment by Michele0303** [comment]
**NEW VERSION RELEASED:**

https://github.com/Michele0303/tiktok-live-recorder/releases/tag/5.0

**Comment by iSuckAtCoding8** [comment]
Sorry to revive an old issue. If you guys are still having issues as I was on the latest 5.2, try adding the session cookie to the cookies.json file. I went from 90% failed recordings on 5.2 to almost 100% success like it was before this room ID dilemma. I guess TikTok is becoming more restrictive like other social media platforms have done.
