### ISSUE TITLE
Manually update 

### ISSUE THREAD

**Issue by Naderrnawar** [Michele0303/tiktok-live-recorder#128]
How to manually update in termux ?

**Comment by iSuckAtCoding8** [comment]
I wasn't able to do it with apt or pkg. I had to do a git pull.

**Comment by Naderrnawar** [comment]
> I wasn't able to do it with apt or pkg. I had to do a git pull.

Can you write the command?

**Comment by iSuckAtCoding8** [comment]
> > I wasn't able to do it with apt or pkg. I had to do a git pull.
> 
> Can you write the command? I tried '' git pull'' but still 4.1 only

Try
`git clone https://github.com/Michele0303/tiktok-live-recorder`
Before
`git pull`

**Comment by Naderrnawar** [comment]
> > > I wasn't able to do it with apt or pkg. I had to do a git pull.
> > 
> > 
> > Can you write the command? I tried '' git pull'' but still 4.1 only
> 
> Try `git clone https://github.com/Michele0303/tiktok-live-recorder` Before `git pull`


fatal: destination path 'tiktok-live-recorder' already exists and is not an empty directory.

If it's nothing I can do, how to delete it to reinstall again?

**Comment by GitFOSSinstead** [comment]
Have you tried typing "cd tiktok-live-recorder" then using git pull?

**Comment by Michele0303** [comment]
I will implement it in the next versions
