### ISSUE TITLE
The system cannot find the specified file

### ISSUE THREAD

**Issue by Oiserium222** [Michele0303/TikTok-Live-Recorder#13]
VERSION: 2.3

[*] USERNAME 
[*] ROOM_ID 7210316480876186373

[*] URL M3U8 http://pull-hls-l1-va01.tiktokcdn.com/stage/stream-2994964971289051186_or4/playlist.m3u8

[*] RECORDING... [PRESS *ONLY ONCE* CTRL + C TO STOP]
[WinError 2] The system cannot find the specified file

**Comment by electrifying84** [comment]
same here

**Comment by Michele0303** [comment]
Download the new version
