### ISSUE TITLE
 ERROR - 'stream_url'

### ISSUE THREAD

**Issue by orhogi** [Michele0303/tiktok-live-recorder#130]
![image](https://github.com/user-attachments/assets/805e2975-4f4a-4289-a2f9-4203a1c68e09)

**Comment by Michele0303** [comment]
It can't find stream_url because the response is:

`{'data': {'prompts': ''}, 'extra': {'now': 1721388585938}, 'status_code': 4003110}`

I think you have to be authenticated to watch the live

**Comment by Michele0303** [comment]
Try the new version.

- I have improved the description of the error
- I added cookie-based authentication

https://github.com/Michele0303/tiktok-live-recorder/releases
