### ISSUE TITLE
[Tutorial] How to login on cookies

### ISSUE THREAD

**Issue by DraganVictor14** [Michele0303/tiktok-live-recorder#131]
How to use cookies to login?

![IMG_20240720_090838](https://github.com/user-attachments/assets/317a8718-be6b-4eb7-98a1-aff2394ed03b)

**Comment by Hannahkaraibombai** [comment]
I actually don't know how to do that. What's that i need to put on cookies python file?

**Comment by Naderrnawar** [comment]
I think this message because live is restricted

**Comment by devinbaeten** [comment]
Login to TikTok on the web and then launch devtools, locate the cookie called `sessionid_ss` and paste the value into the `cookies.json` file.

**Comment by Xerekros** [comment]
Even after updating the two cookies in the cookies.json file, the error still persists. Any ideas?

**Comment by Michele0303** [comment]
> Even after updating the two cookies in the cookies.json file, the error still persists. Any ideas?

Are you sure the session has not expired? Consequently, the cookie value has changed

**Comment by Xerekros** [comment]
Cookie used expires Feb 02, 2025.
Attempted values acquired from Edge, Firefox and Chrome.

**Comment by wickerxman** [comment]
make sure you copy over both the value and the tt-target-idc, and check the json file for syntax errors
once i made sure the tt-target-idc was exactly the one in devtools (for me it was useast2a that didn't work and changing it to the proper one fixed the issue) 
useast2a is just the default value for that field im guessing

**Comment by vitalyabsolut** [comment]
> make sure you copy over both the value and the tt-target-idc, and check the json file for syntax errors once i made sure the tt-target-idc was exactly the one in devtools (for me it was useast2a that didn't work and changing it to the proper one fixed the issue) useast2a is just the default value for that field im guessing

Hey, 


I tried to login with cookies but it don't work. I opened the "cookies.json" on the "src" folder and i copy/paste my "sessionid_ss", i didn't replaced "useast2a" because on my web cookies the tt-target-idc is "useast2a".


When i try the command : "main.py -url https://vm.tiktok.com/URLOFTHELIVE/ -mode automatic -output C:\Users\ME\Videos\test -ffmpeg" i still have this error " 2024-10-11 19:45:56 - ERROR - Live is private, login required. Please add your cookies to cookies.json".

**Comment by dudu536** [comment]
It works great! Thank you.

**Comment by serkantkaraca** [comment]
Can I copy the cookies from machine A and run the recorder on machine B?

**Comment by Michele0303** [comment]
> Can I copy the cookies from machine A and run the recorder on machine B?

yes

**Comment by Michele0303** [comment]
the guide is ready:

https://github.com/Michele0303/tiktok-live-recorder/blob/main/GUIDE.md#how-to-set-cookies

**Comment by youforgetsomething** [comment]
i have place cookies as shown above and still getting the error : Live is private, login required. Please add your cookies to cookies.jsonhttps://github.com/Michele0303/tiktok-live-recorder/blob/main/GUIDE.md#how-to-set-cookies

**Comment by Michele0303** [comment]
contact me on telegram if it happens again:

@michele0303
