### ISSUE TITLE
Automatic Mode Creating Empty Files

### ISSUE THREAD

**Issue by Xerekros** [Michele0303/tiktok-live-recorder#134]
Automatic mode is creating dozens of 0kb .mp4 files seemingly when checking for the live status of accounts.
flags: -user, -mode automatic, -output, -ffmpeg
Issue occurs both on instance where enums.py has been edited to check at shorter intervals and on stock instance.

**Comment by sotero1113** [comment]
Does this user typically have bad connection? I notice some users lives can be laggy and it would disconnect them for a few seconds which can cause this to happen. You can add a check based on the duration so that records below a certain duration arent created

**Comment by Xerekros** [comment]
It does not seem to correlate with when the user in question is live, though the minimum duration does sound like a good feature.

The timings and number of files created are seemingly arbitrary, and it happens on nearly every user since the latest version.

**Comment by Xerekros** [comment]
I was able to grab a screenshot of the error as it made an empty file (I couldn't copy the text)
![error](https://github.com/user-attachments/assets/03a21df3-a74c-46b6-a019-1c4b37320fa6)

**Comment by Michele0303** [comment]
Fixed in https://github.com/Michele0303/tiktok-live-recorder/releases/latest
