### ISSUE TITLE
Can't install dependencies on Windows 

### ISSUE THREAD

**Issue by SpectyteCovelight** [Michele0303/tiktok-live-recorder#135]
When I try to install the dependencies it shows as error 

it appears like that 

C:\windows\system32\tiktok-live-recorder\src> pip install -r requirements.txt
pip : El término 'pip' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable.
Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e
inténtelo de nuevo.

"ENGLISH"
The term 'pip' is not recognized as the name of a cmdlet, function, script file, or executable program. Check if you typed the name correctly, or if you included a path, verify that the path is correct and Please try again."

En línea: 1 Carácter: 1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

How can I fix it?

**Comment by Michele0303** [comment]
Try:

pip3 install -r requirements.txt

**Comment by SpectyteCovelight** [comment]
It didn't work :(

**Comment by Michele0303** [comment]
Are you sure you have python3 installed?
