### ISSUE TITLE
FFMPEG-Python installs but errors out.

### ISSUE THREAD

**Issue by mattyuhh** [Michele0303/tiktok-live-recorder#138]
Have reinstalled everything a couple of times and when setting an automatic flag, ffmpeg and auto convert it will give an error that ffmpeg is not installed even with pip install ffmpeg-python run many times.

**Comment by Michele0303** [comment]
Did you also install ffmpeg? https://www.ffmpeg.org/

**Comment by Michele0303** [comment]
https://www.youtube.com/watch?v=OlNWCpFdVMA

**Comment by vioan** [comment]
I have a similar error, even if ffmpeg is installed. It seems that the ffmeg package for python 3 in ubuntu 24.x is not available. Any idea?
