### ISSUE TITLE
Random FINISH error when initiating new recordings 

### ISSUE THREAD

**Issue by MexTrx** [Michele0303/TikTok-Live-Recorder#14]
When running a new recording on Windows 10 python version 11 _.\main.py -user weathernewslive -mode automatic,_ the script will display the below several times as a group. 

[*] RECORDING... [PRESS *ONLY ONCE* CTRL + C TO STOP]
[*] FINISH TK_weathernewslive_2023.03.14_13-50-17.mp4
[*] URL M3U8

**Comment by Michele0303** [comment]
duplicate #15

**Comment by MexTrx** [comment]
Yes both are installed.
