### ISSUE TITLE
Can't find tiktok room_id anymore?

### ISSUE THREAD

**Issue by fastmango** [Michele0303/tiktok-live-recorder#140]

**Comment by Michele0303** [comment]
it works for me

**Comment by dudu536** [comment]
I feel the same. Some things work, but others don’t.

**Comment by Michele0303** [comment]
Are you using cookies?

**Comment by davidds15** [comment]
![image](https://github.com/user-attachments/assets/b5a8b1ea-b7bc-4d26-a01c-108ad96e4823)
i have the same issue, usually before i can find the room_id from inspect but now i cant find it

**Comment by sotero1113** [comment]
> ![image](https://private-user-images.githubusercontent.com/83685522/360532712-b5a8b1ea-b7bc-4d26-a01c-108ad96e4823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NjQwODcsIm5iZiI6MTcyNDQ2Mzc4NywicGF0aCI6Ii84MzY4NTUyMi8zNjA1MzI3MTItYjVhOGIxZWEtYjdiYy00ZDI2LWEwMWMtMTA4YWQ5NmU0ODIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDAxNDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NjdjNzU5MmY0YjBkNTQyM2Q1ODA5NjM2MzZkMTdiYjI2Mjc2NGY0ZjUzODljMDY1ZjE5ODVhZDgyMzFmZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PBY8IlTdDEN9tYRchJI-tFJi3y7Z3Ur9Xk2zgyAwGXU) i have the same issue, usually before i can find the room_id from inspect but now i cant find it

try room_Id, i had to update mine

**Comment by davidds15** [comment]
![image](https://github.com/user-attachments/assets/547a17a4-25e4-479e-b497-c5195024f4e8)
i tried using username, url but it say no room id found, and i cant find the room id manually from inspect element

**Comment by Michele0303** [comment]
I cannot replicate the problem. The room_id I find it

**Comment by davidds15** [comment]
![image](https://github.com/user-attachments/assets/230a366d-270e-4a88-80ad-698149eda0c2)
somehow today the roomid show up, maybe its the tiktok in my region (?) anyway good work and thank youu everyone cheers

**Comment by dudu536** [comment]
I manually found the room_id, but I don’t know what to do next. Could you please help me?

**Comment by Michele0303** [comment]
> I manually found the room_id, but I don’t know what to do next. Could you please help me?

python3 main.py -room_id placehereroomid

**Comment by dudu536** [comment]
> > I manually found the room_id, but I don’t know what to do next. Could you please help me?
> 
> python3 main.py -room_id placehereroomid

I’ll give it a try. Thank you.
