### ISSUE TITLE
"ERROR - Unable to find room_id. I'll try again in 2 minutes"

### ISSUE THREAD

**Issue by Cptmamba5000** [Michele0303/tiktok-live-recorder#143]
Im a bot when it comes to this stuff. A friend helped me get it set up but I have no idea to fix this any help would be greatly appreciated 👍

**Comment by Michele0303** [comment]
Add cookies

**Comment by Cptmamba5000** [comment]
> Add cookies

Is there any way you can tell me how I can do this? If not maybe a place I can learn to do this? Sorry for inconvenience.
