### ISSUE TITLE
FFMPEG Error

### ISSUE THREAD

**Issue by gritproxy** [Michele0303/tiktok-live-recorder#147]
Hi,

I keep getting an FFMPEG error when attempting to convert files to MP4, and the error doesn't properly log on stderr. All I get is:

ERROR - ffmpeg error (see stderr output for detail)

FFMPEG is properly installed. I've ran the pip install command and I've downloaded ffmpeg - I've even tried all libraries and codecs (standard, shared, full), having them all installed at once and all installed individually. None work.

**Comment by Michele0303** [comment]
try the new version
