### ISSUE TITLE
Any update on adding the room chat to be recorded as well?

### ISSUE THREAD

**Issue by treyp268** [Michele0303/tiktok-live-recorder#149]

**Comment by jamalsoueidan** [comment]
Why do you want the chat to also be recorded?

**Comment by Kaimeera** [comment]
> Why do you want the chat to also be recorded?

I don't know why the other person wants chat recorded, but some creators don't read the comment they are responding to out loud... So if I could get chat outputting to a file it would help.

**Comment by treyp268** [comment]
Honestly its just a preference. When rewatching a live, I like to see when comments come through. IMO having an option to turn it on or off would be nice.
