### ISSUE TITLE
Recording stops before the set duration

### ISSUE THREAD

**Issue by ashketchumpk** [Michele0303/tiktok-live-recorder#150]
I have been getting this issue since the beginning of use of the script, which is : the recording process stops before the end of the duration that I set.

each time it stops at a random duration and all of them were shorter than the duration I specified.

![tiktok live recorder](https://github.com/user-attachments/assets/25a0983d-7deb-4ca4-878c-f0b8a40eeb0f)

Ps : Whenever the recording stops, I check my internet connection, and if the live I am recording is still going on - and everything was alright, so the issue is coming from the script.

**Comment by sotero1113** [comment]
if the live loses connection, or the user pauses the live, or the user joins another live room this can cause the recording to end early since TT generates a new room.

What I did was added a loop so that it rechecks if a user is still live in which it will try 5 times every 10 seconds, if a user is still live then it starts a new recording

**Comment by ashketchumpk** [comment]
Thanks for your input.
I was thinking about the same solution you implemented, but for the purpose of automating the recording process not for the issue that I have encountered. 
for the problem I have faced, my focus went on the system/hardware side thinking that maybe my system (windows) suspends the scripts to allocate the resources to more "urgent" processes. 

But now I will focus on implementing your solution, and hopefully it satisfies the two goals I want to achieve.

Could you please tell me how do you detect if a user is live or not ? since I don't know if I have to scrape the whole profile page of the user (using requests and bs4) to get the "live" tag, or maybe use cleaner and simpler solution (such as an API, assuming there is one).

**Comment by sotero1113** [comment]
There already a method in the repo that checks if a user is online you can just reuse it. After a video is finished recording I make a API request to upload it to Google Cloud Storage

**Comment by ashketchumpk** [comment]
I will look for the method and re-implement it the same way as you did.
Good thinking about the API and uploading thing, you giving some cool ideas honestly.
