### ISSUE TITLE
NotOpenSSLWarning

### ISSUE THREAD

**Issue by Hoax017** [Michele0303/tiktok-live-recorder#151]
I got this warning :

/Users/hoax/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020

<img width="1718" alt="Capture d’écran 2024-10-17 à 23 11 16" src="https://github.com/user-attachments/assets/856863b5-afb4-4b87-8e91-cd7ee0b460a4">

**Comment by inkogandersnito** [comment]
Python version?

**Comment by Hoax017** [comment]
> Python version?

3.13

**Comment by inkogandersnito** [comment]
I know changes has been made but I don't remember in what version. I have this project running smoothly on 3.9.11.
