### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Naderrnawar** [Michele0303/tiktok-live-recorder#153]
![Screenshot_20241106_093402](https://github.com/user-attachments/assets/4fa9745e-51c8-43eb-b95f-509168743e60)

Some recorded lives are broken the audio is okay but the video stay like this photo for more than 10 minutes sometimes it's fix for the same video and sometimes still like this until end

**Comment by Michele0303** [comment]
Prova la nuova versione e fammi sapere se risuccede.

https://github.com/Michele0303/tiktok-live-recorder/releases/latest

**Comment by Michele0303** [comment]
> @Michele0303 I did more recording and I think it's still mostly random, I have now a 15 minutes recording with... 11 seconds usable and 14 minutes and 50 seconds of artifacts with version 5.7

I have no idea, I think it's a tiktok problem.
