### ISSUE TITLE
Issues when stream or connection are not stable

### ISSUE THREAD

**Issue by roberto-sartori-gl** [Michele0303/tiktok-live-recorder#158]
So, sometimes the stream, the internet connection, tiktok itself or the streamer internet connection are not stable. In this situation, the recorded file is very small as the recording ends at the first connectivity issue - or if automatic recording is used, a lot of small files are generated.

I think this is the case even when the streamer 'pauses' the live (but I couldn't confirm this).

Various recording tools (even fork of this one!) 'solved' the problem concatenating all the files after the live actually ends. Is there any plan to include something like this?

There are also various ffmpeg options that could be used (reconnect_streamed, reconnect_delay_max) which may be useful.

**Comment by Michele0303** [comment]
Hi Roberto, to solve the problem, I was thinking of exploring some options in ffmpeg, like reconnect_streamed, etc.

**Comment by Michele0303** [comment]
Fixed in: https://github.com/Michele0303/tiktok-live-recorder/releases/tag/5.5

**Comment by Michele0303** [comment]
Are you using version 5.7?

**Comment by Michele0303** [comment]
If that ffmpeg command solves the problem, then version 5.8 will work correctly
