### ISSUE TITLE
ERROR - Live is private, login required. Please add your cookies to cookies.json

### ISSUE THREAD

**Issue by Ecdldaiiere** [Michele0303/tiktok-live-recorder#167]
How to fix this issue? This is an age-restricted stream and I have checked and double checked the cookies are correct in the cookies.json. 

Am using the command: python main.py -user (username)

**Comment by RealityQuizzicality** [comment]
{
  "sessionid_ss": "did you paste cookie here?",
  "tt-target-idc": "useast2a"
}

**Comment by hhoyyoo** [comment]
> in cookies.json
> 
> { "sessionid_ss": "did you paste cookie here?", "tt-target-idc": "useast2a" }

i have the same problem and already copied the cookie but still telling me to add cookie
pls help

**Comment by RealityQuizzicality** [comment]
> > in cookies.json
> > { "sessionid_ss": "did you paste cookie here?", "tt-target-idc": "useast2a" }
> 
> i have the same problem and already copied the cookie but still telling me to add cookie pls help

all i did was go to tiktok.com/live and login, then open developer tools click storage then click tiktok under cookies and copied the value of sessionid_ss then pasted in cookie.json in between the  quotes like above.

**Comment by hhoyyoo** [comment]
> > > in cookies.json
> > > { "sessionid_ss": "did you paste cookie here?", "tt-target-idc": "useast2a" }
> > 
> > 
> > i have the same problem and already copied the cookie but still telling me to add cookie pls help
> 
> all i did was go to tiktok.com/live and login, then open developer tools click storage then click tiktok under cookies and copied the value of sessionid_ss then pasted in cookie.json in between the quotes like above.

same. i wonder where i did wrong

**Comment by RealityQuizzicality** [comment]
> > > > in cookies.json
> > > > { "sessionid_ss": "did you paste cookie here?", "tt-target-idc": "useast2a" }
> > > 
> > > 
> > > i have the same problem and already copied the cookie but still telling me to add cookie pls help
> > 
> > 
> > all i did was go to tiktok.com/live and login, then open developer tools click storage then click tiktok under cookies and copied the value of sessionid_ss then pasted in cookie.json in between the quotes like above.
> 
> same. i wonder where i did wrong

are you still logged in on tiktok, i think in a different post it says not to logout or use extensions that delete cookies or you'll have to get the new cookie and start again.

other than that i have no idea, sorry.

**Comment by hhoyyoo** [comment]
> > > > > in cookies.json
> > > > > { "sessionid_ss": "did you paste cookie here?", "tt-target-idc": "useast2a" }
> > > > 
> > > > 
> > > > i have the same problem and already copied the cookie but still telling me to add cookie pls help
> > > 
> > > 
> > > all i did was go to tiktok.com/live and login, then open developer tools click storage then click tiktok under cookies and copied the value of sessionid_ss then pasted in cookie.json in between the quotes like above.
> > 
> > 
> > same. i wonder where i did wrong
> 
> are you still logged in on tiktok, i think in a different post it says not to logout or use extensions that delete cookies or you'll have to get the new cookie and start again.
> 
> other than that i have no idea, sorry.

yep. logged in on 2 browsers + 2 android + 1 ios
thx anyway for the help.

**Comment by Michele0303** [comment]
Have you followed these steps correctly?

https://github.com/Michele0303/tiktok-live-recorder/blob/main/GUIDE.md#how-to-set-cookies
