### ISSUE TITLE
Stops recording instantly

### ISSUE THREAD

**Issue by joemustafa** [Michele0303/TikTok-Live-Recorder#17]
I use both the username and room_id and it starts to record then stops instantly for some streams others work fine

room_id is 7211316397049645870
my_env) ubuntu@ubuntu-ub:/media/jmustafa/1TB_1/API/TikTok2/TikTok-Live-Recorder$ python main.py -room_id 7211316397049645870

  _____ _ _   _____    _     _    _           ___                   _         
 |_   _(_) |_|_   _|__| |__ | |  (_)_ _____  | _ \___ __ ___ _ _ __| |___ _ _ 
   | | | | / / | |/ _ \ / / | |__| \ V / -_) |   / -_) _/ _ \ '_/ _` / -_) '_|
   |_| |_|_\_\ |_|\___/_\_\ |____|_|\_/\___| |_|_\___\__\___/_| \__,_\___|_| 

   V2.5

[*] ROOM_ID 7211316397049645870

[*] URL M3U8 

[*] STARTED RECORDING... [PRESS ONLY ONCE CTRL + C TO STOP]
[*] FINISH TK_isthislittlelunargirl_2023.03.17_01-31-02.mp4
(my_env)

This is the error.log
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by Michele0303** [comment]
![image](https://user-images.githubusercontent.com/31160531/225794710-b35d9d34-9211-460b-81ad-aa7f2481f9e5.png)

For some reason the stream url is not present in the api

**Comment by joemustafa** [comment]
Yea just noticed that. Happening on alot of the streams. Wonder if it is a setting so we can not see it

**Comment by Michele0303** [comment]
Unfortunately, I have no way to solve
