### ISSUE TITLE
Program randomly closes while monitoring

### ISSUE THREAD

**Issue by fulopsoma23** [Michele0303/tiktok-live-recorder#180]
Since the new update, the program closes completely randomly while monitoring. Is there a solution?

**Comment by Michele0303** [comment]
Can you provide me with more information? Maybe screenshots

**Comment by jotherthings** [comment]
everytime I run the program, it always checking and installing dependencies for about 5-10 minutes, even if I just run -h.  When finished checking it  also takes 5-10 minutes to start downloading

**Comment by Michele0303** [comment]
Can you provide some screenshots?

What operating system are you using?
What version of python are you using?
Do you use a virtual enviroment (venv)?

**Comment by jotherthings** [comment]
Sorry, I think it's because my internet connection, when I change my internet source it solved the problem.
