### ISSUE TITLE
update v5.5 breaks the automatic mode

### ISSUE THREAD

**Issue by birizui** [Michele0303/tiktok-live-recorder#181]
Hey, thanks for the constant update. However, I found out that the latest update (v5.5) breaks the automatic mode when the connection is not stable or the target account got some connection problems. 

I used this prompt: python main.py -user (username) -output /sdcard/Documents -mode automatic -duration 150 

And failed mid downloading and got this message:
[*] Started recording for 150 seconds                           
[*] [PRESS CTRL + C ONCE TO STOP]                               
[!] ('Connection broken: IncompleteRead(3041 bytes read, 1055 more expected)', IncompleteRead(3041 bytes read, 1055 more expected))                                                             
~/tiktok-live-recorder/src $

Hopefully we can get a fix for this soon. 
Also, if it's possible please give us option not to get auto update to the newest version of this app. Because v5.3 and v5.4 worked really well for me. 
Thank you

**Comment by birizui** [comment]
One more, please bring back the timestamps while rechecking if the user went live or not because in v5.4 and v5.5 we only received this message (while in v5.3 we also got the timestamps of the refreshing):

[*] The user is not currently live.                            
 [*] waiting 5 minutes before recheck

**Comment by birizui** [comment]
One more, apparently after the v5.5 update the duration prompt that I use also doesn't work anymore. I always split them into 150 seconds clips, and currently it doesn't seem to work anymore. The program won't automatically stop after 150 seconds. Please take a look at this as well. Or if there's a way to revert back to v5.4 that'd be helpful. Thank you.

**Comment by Michele0303** [comment]
Thank you for the great feedback. I should have solved it in version 5.6
