### ISSUE TITLE
automatic mode 'connection broken' v5.6

### ISSUE THREAD

**Issue by birizui** [Michele0303/tiktok-live-recorder#182]
Thank you so much for the quick response. I'm testing the newest version right now, and the 'connection broken' for the automatic mode still occurs in v5.6 version. 

[*] 2024-12-28 04:13:34 - Started recording for 150 seconds
[*] 2024-12-28 04:13:34 - [PRESS CTRL + C ONCE TO STOP]
[!] 2024-12-28 04:15:00 - ('Connection broken: IncompleteRead(3065 bytes read, 1031 more expected)', IncompleteRead(3065 bytes read, 1031 more expected))
~/tiktok-live-recorder/src $

I'm not sure what happened, but when there were connection problems in v5.3 or v5.4 (AUTOMATIC mode), termux wouldn't stop and instead would retry (loop) to this process again: 'Started recording for 150 seconds'. It'd only stop once I pressed CTRL+C

However in v5.5 and v5.6 it'll stop completely and back to this message '~/tiktok-live-recorder/src $' eventho i didn't press CTRL+C.

Hopefully it's clear enough. Thanks again

**Comment by Michele0303** [comment]
Very strange, did the old version show you a different error/message?

**Comment by birizui** [comment]
> Very strange, did the old version show you a different error/message?

The v5.3 and v5.4 didn't have this problem for the automatic mode. They would keep looping the prompt until I pressed CTRL+C manually to stop the process.

**Comment by Michele0303** [comment]
can you try it now?

**Comment by birizui** [comment]
> can you try it now?

I've tried it, it works again! Thank you so much 😊
