### ISSUE TITLE
Unexpected Error after a few minutes ?

### ISSUE THREAD

**Issue by CallMePapa404** [Michele0303/tiktok-live-recorder#183]
For the last weeks now, the recorder has rarely worked as it should. I had no problems with the automatic mode or ffmpeg for the last half year but now most of the files are corrupted. with VLC I can play them back but apparently the “end” is missing, rewinding is not possible. i get the following error code after about 5 minutes (windows 10 and automatic mode enabled) :  
Unexpected error: ('Connection broken: IncompleteRead(0 bytes read, 2 more expected)', IncompleteRead(0 bytes read, 2 more expected))
or 
 Unexpected error: ('Connection broken: IncompleteRead(3697 bytes read, 399 more expected)', IncompleteRead(3697 bytes read, 399 more expected))
it can't be my internet connection.
Thank you for your work on this project !

**Comment by Michele0303** [comment]
So the problem is solved? #182

**Comment by Michele0303** [comment]
> so far it seems like it is solved, thank you very much
> 
> is there a way to stop the automatic mode except CTRL+C to save and closing the window completely?

It is not possible to change modes in real time
