### ISSUE TITLE
a little explanation needed about new mod option v5.6, 5.7.

### ISSUE THREAD

**Issue by youforgetsomething** [Michele0303/tiktok-live-recorder#184]
is you removed the auto encode and add the conversion after the desired duration finished ?
that take time to process maybe ?..
the mode auto or manual referes to the track when account is online or it's for ffmpeg real time conversion ? or you just removed that real time conversion as it reason for destroyed "pixelated , boxed" video output ?
, can be an option linke , keep recordings at .flv and the user manually convert them later ? in case of setting low duration like 5 minutes it keep remake new files after 'like instance 5 minutes' and immediately start new file as keep with the stream without waiting the flv file to convert ?

**Comment by Michele0303** [comment]
The flv to mp4 conversion is instant.

I removed the recording via ffmpeg because I felt it was unnecessary
