### ISSUE TITLE
hang after streamer goes offline and not monitor it anymore cuz this hang for sure.

### ISSUE THREAD

**Issue by youforgetsomething** [Michele0303/tiktok-live-recorder#185]
giving this error after streamer goes offline :
Unexpected error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

and hang on that and must close it manually + fixing the video 'even in case it fully downloaded , because that can happen anytime without streamer goes offline' . that error if streamer goes offline happens instead of converting the file to mp4 and waiting for next online stat , hang = freeze at this point. that make everything as it's not exist , if it hangs it's over  , nothing can happen but come and check it manually and halt this and try to fix the file 'if it even can be..' ..keep these things in mind please and try to fix them .

**Comment by Michele0303** [comment]
With version 5.8 it should work
