### ISSUE TITLE
error

### ISSUE THREAD

**Issue by guitiba05** [Michele0303/TikTok-Live-Recorder#20]
|_   _(_) |_|_   _|__| |__ | |  (_)_ _____  | _ \___ __ ___ _ _ __| |___ _ _
   | | | | / / | |/ _ \ / / | |__| \ V / -_) |   / -_) _/ _ \ '_/ _` / -_) '_|
   |_| |_|_\_\ |_|\___/_\_\ |____|_|\_/\___| |_|_\___\__\___/_| \__,_\___|_|

   V2.8

[*] USERNAME eujulud
[*] ROOM_ID 7212100239732312837

[*] URL M3U8 http://pull-hls-f11-va01.tiktokcdn.com/stage/stream-2994992854081208393_or4.m3u8

[*] STARTED RECORDING... [PRESS ONLY ONCE CTRL + C TO STOP]
[*] FINISH TK_eujulud_2023.03.19_03-57-57.mp4
[*] URL M3U8 http://pull-hls-f11-va01.tiktokcdn.com/stage/stream-2994992854081208393_or4.m3u8

[*] STARTED RECORDING... [PRESS ONLY ONCE CTRL + C TO STOP]
[*] FINISH TK_eujulud_2023.03.19_03-58-13.mp4
[*] URL M3U8 http://pull-hls-f11-va01.tiktokcdn.com/stage/stream-2994992854081208393_or4.m3u8

[*] STARTED RECORDING... [PRESS ONLY ONCE CTRL + C TO STOP] /

**Comment by Michele0303** [comment]
I'm working on it

**Comment by Michele0303** [comment]
https://github.com/Michele0303/TikTok-Live-Recorder/releases/tag/2.9
