### ISSUE TITLE
2.8 -> 3.0 (doesn't show length on clips anymore?)

### ISSUE THREAD

**Issue by KevinDurantsBurner** [Michele0303/TikTok-Live-Recorder#25]
Hi,

I use loslesscut to merge all the files together and i noticed it doesn't show the length anymore from upgrading to 2.8 to 3.0? 

just wondering if using older version is more reliable than new version for now (streamlink vs youtube-dl)

![image](https://user-images.githubusercontent.com/129896411/229897399-cd3f1f50-1743-4dcd-bd8f-e26b88aae58d.png)

**Comment by KevinDurantsBurner** [comment]
also i just noticed that the clips do not have thumbnail previews anymore

**Comment by Michele0303** [comment]
About thumbnail and length you should ask streamlink. Maybe it can be fixed with some settings
