### ISSUE TITLE
No scheme supplied?

### ISSUE THREAD

**Issue by MexTrx** [Michele0303/TikTok-Live-Recorder#3]
Was able to get it working for a bit, then it started to display the error below. It did supply the proper roomID and username. 

[*] ROOM_ID: <RoomID>
[*] USERNAME: <username>
[*] URL M3U8
[*] URL FLV

[*] RECORDING...
Invalid URL '': No scheme supplied. Perhaps you meant http://?

**Comment by Michele0303** [comment]
Can you show me the url in output?
Telegram: @Michele0303
Email: michele8.fiori8@gmail.com
