### ISSUE TITLE
How to set output?

### ISSUE THREAD

**Issue by KevinDurantsBurner** [Michele0303/TikTok-Live-Recorder#30]
Hi i've stuck to using 2.8 but have now switched over to 3.3 and updated my requirements.

When setting a recording and an output i don't see the video anywhere.. I've tried setting an output by doing

main.py -user account -mode automatic -output C:\Users\Profile\Downloads\TikTok-Live-Recorder-3.3\videos

which then shows

```
[*] STARTED RECORDING... [PRESS ONLY ONCE CTRL + C TO STOP]
[*] FINISH C:\Users\Profile\Downloads\TikTok-Live-Recorder-3.3\videos\TK_account_2023.05.09_00-19-01.mp4
[*] URL M3U8 https://pull-f5-va01.tiktokcdn.com/stage/stream-1234_or4.flv
```

and also not setting an output

main.py -user account -mode automatic

```
[*] STARTED RECORDING... [PRESS ONLY ONCE CTRL + C TO STOP]
[*] FINISH NoneTK_account_2023.05.09_00-19-40.mp4
[*] URL M3U8 https://pull-f5-tt01.tiktokcdn.com/stage/stream-1234_or4.flv
```

but neither seems to actually save the video anywhere or at least i dont see it anywhere..

Any idea why?

**Comment by Michele0303** [comment]
Do you have an info.log or error.log file to show me?

**Comment by KevinDurantsBurner** [comment]
> Do you have an info.log or error.log file to show me?

i have tried 3.4 and it is now downloading fine however i seem to be noticing a lot more

` Unable to find room_id. I'll try again in 120 minutes`

when typing just the username even though they are live, forcing to restart and try again multiple times before it actually record. Not sure if thats a tiktok thing or your app.

**Comment by Michele0303** [comment]
Unfortunately tiktok rejects some requests, it is still not clear to me based on what. I will try to get the information on different endpoints in the next release.
