### ISSUE TITLE
FFMpeg YES and NO

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [Michele0303/TikTok-Live-Recorder#31]
Allow `-y` and `-n` args to always say yes or no to ffmpeg conversions.

**Comment by KevinDurantsBurner** [comment]
or another suggestion is if -mode automatic to just automatically convert so it can go back to looking for the live again

appreciate all the work u do op

**Comment by TheDrawingCoder-Gamer** [comment]
> or another suggestion is if -mode automatic to just automatically convert so it can go back to looking for the live again
> 
> appreciate all the work u do op

this is basically WHY i suggest it, so I can always convert it in auto mode
