### ISSUE TITLE
FFMpeg in the background

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [Michele0303/TikTok-Live-Recorder#32]
Because lives sometimes stutter/break connection, mp4s sometimes get ended early. This means that if a `-y` option was added and was called, it would spend a while fixing up the mp4 while a live is still going on. If ffmpeg was sent to the background somehow on multithreaded systems, new lives can immediately be recorded while conversion is going on.

**Comment by Michele0303** [comment]
I will modify in such a way, that it will directly happen the download with ffmpeg, if it is present -y

**Comment by TheDrawingCoder-Gamer** [comment]
> I will modify in such a way, that it will directly happen the download with ffmpeg, if it is present -y

if I am reading ffmpeg, you can directly convert m3u8 to mkv

**Comment by Michele0303** [comment]
> > I will modify in such a way, that it will directly happen the download with ffmpeg, if it is present -y
> 
> if I am reading ffmpeg, you can directly convert m3u8 to mkv

Sometimes the m3u8 link cannot be found, that's why I prefer to download with flv

**Comment by TheDrawingCoder-Gamer** [comment]
> > > I will modify in such a way, that it will directly happen the download with ffmpeg, if it is present -y
> > 
> > 
> > if I am reading ffmpeg, you can directly convert m3u8 to mkv
> 
> Sometimes the m3u8 link cannot be found, that's why I prefer to download with flv

You are right, I modified my local version and got a 404. there goes ~30 minutes of custom wood burning footage LOL
