### ISSUE TITLE
Question about recording saving

### ISSUE THREAD

**Issue by Liam942** [Michele0303/tiktok-live-recorder#35]
I  have been using this program for a few days and it works great. Don't know too much about programming so might be completely off.

I use the program on windows 10 in both cmd and powershell. usually automatic mode and sometimes manual. 
My internet connection is strong, which means I am not the one losing connection.

Is it possible to add a small delay to saving recordings so that they don't end directly when the user lags for a second?
  often the recording continues under small lag, but sometimes it stops completely when faced with a small lag from the user.
  This often happens when another tiktok accounts joins the live, creating a split screen  / battle.

When I use automatic mode the recording usually ends at the lag and then a new starts directly. In this possible to fix?

**Comment by Michele0303** [comment]
It would complicate things a lot
