### ISSUE TITLE
Unable to find stream url

### ISSUE THREAD

**Issue by oscarchen82** [Michele0303/TikTok-Live-Recorder#36]
Windows 11 system,  Python 3.10.9， TIktok-Live-Recorder V3.6
Command : python main.py -user long0481gjc -output D:/ -ffmpeg
Output: 
Expecting value: line 1 column 1 (char 0)
[-] Unable to find stream url.

I dont know whats wrong

**Comment by Michele0303** [comment]
Sometimes tiktok does not provide the cdn of the stream. Unfortunately, I haven't found any solutions yet
