### ISSUE TITLE
Unable to find room_id.

### ISSUE THREAD

**Issue by guitiba05** [Michele0303/TikTok-Live-Recorder#37]
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[*] wardadallagnol is offline
waiting 5 minutes before recheck

[*] wardadallagnol is offline
waiting 5 minutes before recheck

[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes
[-] Unable to find room_id. I'll try again in 2 minutes

**Comment by Michele0303** [comment]
I think I understand the problem.

I will modify this line for the next version:

https://github.com/Michele0303/TikTok-Live-Recorder/blob/main/tiktokbot.py#L171

**Comment by BrotherWebmaster** [comment]
This is all mine does this as well unfortunately. I have double and triple checked everything and I can't figure out what the problem is. It fins the room_id sometimes like above.

**Comment by Sullyscharger** [comment]
> This is all mine does this as well unfortunately. I have double and triple checked everything and I can't figure out what the problem is. It fins the room_id sometimes like above.

Yeah I've been getting this same issue as well recently.

**Comment by Michele0303** [comment]
https://github.com/Michele0303/tiktok-live-recorder/issues/70#issuecomment-1707392528
