### ISSUE TITLE
automatic vs manual

### ISSUE THREAD

**Issue by Liam942** [Michele0303/tiktok-live-recorder#38]
When I first downloaded the program I used the settings python main.py -user
A consistant problem I found was that around 10-20% files were "too long" in both vlc and could not be uploaded to youtube. The length of the actual recording did not seem to matter, I converted them in vlc and it worked but took time.
I had the same problem when I used the website tiktokrecorder that eventually stopped working, so its not specific to this program.

I later used the settings python main.py -mode automatic -ffmpeg -user
all files could be opened normally.  
Now lives that were lagged would start recording again automaticly.

But I noticed now that several recordings had around 10-30 seconds jumpcuts in them. Recordings that should not have any lag.
I assume the live convertion with ffmpeg is causing the issue since I did not notice anything without it.

In case I have missed any setting, is there any way I can ensure a automatic ffmpeg recording does not have these jumpcuts?
Or is it possible to have automatic recording without the ffmpeg?

**Comment by Michele0303** [comment]
The jumps could be caused by lag in your connection or by the live host
