### ISSUE TITLE
ffmpeg can't determine the video codec

### ISSUE THREAD

**Issue by booleangit** [Michele0303/tiktok-live-recorder#39]
Apparently TikTok has changed something to their streams, because ffmpeg is unable to identify the video codec being used.

**Comment by Michele0303** [comment]
Are you using -ffpmeg or post download conversion?

**Comment by booleangit** [comment]
My apologies. I forgot that I've modified your application a while ago, so it uses ffmpeg by default. I'm using "ffmpeg -i source.flv -c copy dest.ts" to save the stream and "ffmpeg -i dest.ts -c copy final.mp4" to convert the transport stream to mp4. This is the most efficient way to save streams and results in better PQ and smaller files as it doesn't transcode the stream but still provides "real" MPEG-4. TikTok has changed something to their streams which confuses ffmpeg's stream saving functionality, but that's not something you should be bothered with.

**Comment by zylaxabi** [comment]
> 

hey i think im running into the same probelm as you with tiktok live streams. Did you ever find a solution?

**Comment by Jason69421** [comment]
i think tiktok have encrypted their flv files so they cant be played. easiest way to download it is to use "yt-dlp [tiktok live page]" which downloads the m3u8 stream
