### ISSUE TITLE
"Invalid URL" error. Script does not work

### ISSUE THREAD

**Issue by Tempo-c** [Michele0303/TikTok-Live-Recorder#4]
Done in PowerShell 7 on windows 10

Command used:
py main.py -room_id 7276784253637265062 -mode manual

Output: 

  _____ _ _   _____    _     _    _           ___                   _
 |_   _(_) |_|_   _|__| |__ | |  (_)_ _____  | _ \___ __ ___ _ _ __| |___ _ _
   | | | | / / | |/ _ \ / / | |__| \ V / -_) |   / -_) _/ _ \ '_/ _` / -_) '_|
   |_| |_|_\_\ |_|\___/_\_\ |____|_|\_/\___| |_|_\___\__\___/_| \__,_\___|_|

[*] USERNAME: imkevinhart
[*] ROOM_ID: 7276784253637735062
[*] URL M3U8
[*] URL FLV

[*] RECORDING...
Invalid URL '': No scheme supplied. Perhaps you meant http://?

**Comment by Michele0303** [comment]
Try the new version.

When a user has never been live, it is not possible to get the room_id

**Comment by Michele0303** [comment]
From the tests I did, "imkevinhart" has never been live, so you have no way of knowing his room_id

**Comment by minhduc0x** [comment]
def get_room_id(user: 7176763770381814555) -> str:
    tiktok_url = "https://www.tiktok.com/@{shopquangchau_thukid}/live"
    try:
        response = req.get(tiktok_url)
        response.raise_for_status()
        content = response.text
        return re.search("room_id=(.*?)\"/>", content).group(1)

Sorry i'm newbie, why it's Missing user/room id error?

**Comment by spinningsand** [comment]
> > Try the new version.
> > When a user has never been live, it is not possible to get the ro
> 
> the first time when I use it worked, but after I always got this error : HTTPConnectionPool(host='pull-flv-f16-tt02.fcdn.us.tiktokv.com', port=80): Max retries exceeded with url: /stage/stream-35709xxxxx74_or4/index.flv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000268EEAF0D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
> 
> What should got wrong.

I got the same error from everyone I tried, even when they were live. It worked the first time (used manual mode), then I used automatic mode on someone who was offline and noticed it didn't start working when they went online. Now it won't work at all in either mode.

**Comment by 3v3rm4rt3lL** [comment]
> 

I tried with vpns is not a blocking ip, i still have this issue, is something about https and http i think  I tried other code made with node js, and works perfect, every live.

**Comment by spinningsand** [comment]
> > 
> 
> I tried with vpns is not a blocking ip, i still have this issue, is something about https and http i think I tried other code made with node js, and works perfect, every live.

What's the other code?

**Comment by 3v3rm4rt3lL** [comment]
Thank you Michele.

**Comment by spinningsand** [comment]
Any updates?

**Comment by Michele0303** [comment]
Fixed

**Comment by 3v3rm4rt3lL** [comment]
How can I get work youtube-dl.exe on linux ? Thanks.

**Comment by 3v3rm4rt3lL** [comment]
> How can I get work youtube-dl.exe on linux ? Thanks.

got it, thanks.

**Comment by Michele0303** [comment]
> How can I get work youtube-dl.exe on linux ? Thanks.

https://phoenixnap.com/kb/install-ffmpeg-ubuntu

Try this or search on google for other distrubution

**Comment by spinningsand** [comment]
I get this error when I try to use it: 

```
'youtube-dl' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by 3v3rm4rt3lL** [comment]
Windows or linux?

**Comment by spinningsand** [comment]
Windows

**Comment by 3v3rm4rt3lL** [comment]
Well, when I running something like this I try run the terminal or powershell where youtube-dl.exe is. And then run it the live tiktok py.

**Comment by spinningsand** [comment]
The tiktok py and youtube-dl are both in the same directory if that's what you mean.

**Comment by 3v3rm4rt3lL** [comment]
And obvsly you terminal is running in the folder path. Right? Because I tested right now and it works for me, pretty well.

**Comment by spinningsand** [comment]
Yes, I go to `cd TikTok-Live-Recorder` before I try using it. The default directory my terminal starts out in is the same one that youtube-dl and the tiktok py are both in.

**Comment by Michele0303** [comment]
> I get this error when I try to use it:
> 
> ```
> 'youtube-dl' is not recognized as an internal or external command,
> operable program or batch file.
> ```
> 
> I have youtube-dl and it's added to my PATH.

Try:
pip install youtube-dl

**Comment by spinningsand** [comment]
> > I get this error when I try to use it:
> > ```
> > 'youtube-dl' is not recognized as an internal or external command,
> > operable program or batch file.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have youtube-dl and it's added to my PATH.
> 
> Try: pip install youtube-dl

Thanks! This did help and it works now. I did notice that the automatic mode doesn't work.  If you run a command in automatic mode when someone is offline, it doesn't start working after they come on. It only says this as if they're still offline:

```
[*] [user] is offline
waiting 5 minutes before recheck
```
