### ISSUE TITLE
Recording restarts often during continuous livestream

### ISSUE THREAD

**Issue by MyMi74** [Michele0303/TikTok-Live-Recorder#40]
Records only for a short time, stops and continues with a new file under automatic mode and just stops with manual Mode, resulting in many small files of the recording.

Anyone knows a fix?

Otherwise works great, very nice work, thank you

**Comment by Michele0303** [comment]
Try using -ffmpeg flag

**Comment by MyMi74** [comment]
It was using the ffmpeg flag, wouldnt let me start automatic mode without it 

Thx alot for the reply 🙏

**Comment by vanyamlb** [comment]
Can you explain please how to use it? Where do you get room id from? It doesn't work by username @MyMi74

**Comment by Michele0303** [comment]
> Can you explain please how to use it? Where do you get room id from? It doesn't work by username @MyMi74
> 
> @Michele0303 I also tried to reach you on telegram
> 
> UPD: so it's running, but can't find ffmpeg-python installed on my mac :/

I replied to you on telegram

**Comment by Michele0303** [comment]
> I was using it for a 4-hour live stream, resulting in 3 files. My mac's display went to sleep and created a new stream when I woke it up. Could this be a cause?

Yes it is that

**Comment by richiec77** [comment]
This is happening to me now.
See the video here
[https://share.cleanshot.com/fD5GPhqN](url)

**Comment by richiec77** [comment]
keeps starting and stopping

**Comment by Michele0303** [comment]
> This is happening to me now. Stream capture keeps starting and stopping every couple seconds. See the video here https://share.cleanshot.com/fD5GPhqN

Update the version, the tool no longer uses m3u8 but flv
