### ISSUE TITLE
Modify delay time

### ISSUE THREAD

**Issue by kraddock** [Michele0303/TikTok-Live-Recorder#41]
Hi & thanks for the great project!

One simple question - how can I modify the delay (waiting/pause) time between rechecks? For example, one particular account I follow runs many short lives throughout the day, sometimes even under 5 minutes each. So I'd like to set 2 minute intervals between rechecks, if possible (even with the risk of running into some IP blocking by TT).

**Comment by Michele0303** [comment]
For now, it is not possible to do this from the command line.
You can still do it by changing:
AUTOMATIC_MODE = 5
to
AUTOMATIC_MODE = 2
in
https://github.com/Michele0303/TikTok-Live-Recorder/blob/main/enums.py#L12
