### ISSUE TITLE
Expecting value: line 1 column 1 (char 0) [-] Unable to find stream url.

### ISSUE THREAD

**Issue by Liam942** [Michele0303/TikTok-Live-Recorder#43]
as of today I got this error output a few times. Restarted my pc and same thing happened. Worked on a few tiktok users but most got this respone.  Tried with and without ffmpeg
![5795074b9cc30bb9032083874e0f5e91](https://github.com/Michele0303/TikTok-Live-Recorder/assets/65906695/f42b52e4-777f-4a48-911f-59a8e062e999)

**Comment by Michele0303** [comment]
Check out the new release
https://github.com/Michele0303/TikTok-Live-Recorder/releases/tag/3.7
