### ISSUE TITLE
Automatic stop recording

### ISSUE THREAD

**Issue by aCS6** [Michele0303/TikTok-Live-Recorder#45]
It would be helpful if users could specify the duration of the recording when starting the program. For example, if a live stream is scheduled to be 1 hour long but the user only wants to record 10 minutes of it, they should be able to input this duration. Once the recording reaches the specified duration (10 minutes in this case), the program should automatically stop.

I am currently conducting research and development to address this requirement. If anyone has any suggestions or opinions regarding this functionality or knows of any existing solutions, please feel free to comment. I am open to exploring different approaches and would appreciate any input or guidance on this matter.

**Comment by aCS6** [comment]
@Michele0303 , I sincerely appreciate your insights and the solutions you provided. However, I would like to clarify my requirements as they differ slightly from the suggestions you made. I do not intend to schedule the recording; instead, I am seeking a way to stop the recording based on user input provided through a command-line argument, if available. I value your understanding and assistance in addressing this specific need.

**Comment by Michele0303** [comment]
Sorry I wasn't specific enough. 
I wanted to show you the -t flag
![image](https://github.com/Michele0303/TikTok-Live-Recorder/assets/31160531/31ae76ae-cdf4-42b1-8dba-f8df50cd30f9)

**Comment by aCS6** [comment]
oh. thanks. I lot of code is going to be reduced.
@Michele0303 would you make the change? or I should give the PR, after the necessary changes ?
thanks, anyway

**Comment by Michele0303** [comment]
You make the changes and then send the PR. Thanks
