### ISSUE TITLE
Video produced is fast forward after a few minutes and with wrong duration

### ISSUE THREAD

**Issue by CyberbobGR** [Michele0303/tiktok-live-recorder#48]
Sometimes the video saved is "corrupted".
For this example there was a 2hour live.

In MPC-BE it shows total duration of 15 minutes, the video is playing fine for about 13 minutes and then the video is in fast forward for the rest 2 minutes.

In VLC it shows 2 hours playtime, but the same thing happens.
Fine for 13 minutes, then fast forward for another 2 minutes and the rest 105 minutes it's only audio playing.

It was recorded with automatic mode and -ffmpeg option.

**Comment by SwissAlps2** [comment]
I would personally switch to using manual mode with out the --ffmpeg option. It seems to generate videos with less playback issues.

**Comment by Michele0303** [comment]
Now all streams are downloaded without ffmpeg
