### ISSUE TITLE
Live has ended but still was showing as recording, pressing "q" didn't work - file can not be opened

### ISSUE THREAD

**Issue by CyberbobGR** [Michele0303/tiktok-live-recorder#49]
Another issue, there was a live that ended, but in the program it was still showing as recording.
I tried to press "q" one time but it didn't work, nothing happened.
I left it for a few minutes and nothing happened, so i tried to press it again a few times with no response.
I had to close the window and the file can not be opened. 

This is the 2nd issue with version 3.7.
Last version I was still using and never had problems was 3.3, but unfortunately it doesn't work anymore.
I hope you can find what is causing the issues and fix them.

Thank you again for your time making this 🙏

**Comment by SwissAlps2** [comment]
Were you using automatic mode? Because automatic mode forces the use of downloading via ffmpeg. If I use automatic mode and the stream times out or doesn't close gracefrully. The video it produces doesn't open. I'm going to revert back to manual mode which uses python for downloading the stream.
