### ISSUE TITLE
Command not Found

### ISSUE THREAD

**Issue by marwcel** [Michele0303/TikTok-Live-Recorder#5]
Done on MacOs in Terminal:

When i open the main.py file in Terminal and i need to enter a command for -user it is not working.

in what formate i have enter the username or room id?
i dont get it to work.

**Comment by Michele0303** [comment]
python main.py -user test123
python main.py -room_id 123456789

**Comment by marwcel** [comment]
now i get this error:

[*] RECORDING... 
HTTPConnectionPool(host='pull-flv-f16-gcp01.tiktokcdn.com', port=80): Max retries exceeded with url: /stage/stream-3282899295543492780_or4/index.flv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd07842c610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

**Comment by Michele0303** [comment]
it will be fixed soon
