### ISSUE TITLE
Error with ffmpeg

### ISSUE THREAD

**Issue by guitiba05** [Michele0303/tiktok-live-recorder#50]
[*] URL FLV https://pull-flv-l1-va01.tiktokcdn.com/stage/stream-2995464857903169586_or4.flv

[*] STARTED RECORDING... [PRESS 'q' TO STOP RECORDING]
ffmpeg error (see stderr output for detail)

**Comment by Michele0303** [comment]
I added the display of ffmpeg errors:
https://github.com/Michele0303/TikTok-Live-Recorder/releases/tag/3.8

**Comment by aCS6** [comment]
Hi, @guitiba05 
Thank you for bringing up this issue! If the latest release has addressed the problem you reported, could you please confirm and consider closing the issue? Your feedback and cooperation in closing resolved issues are greatly appreciated as they help us maintain an organized repository. Please let me know if there's anything else I can assist you with. Thank you for your understanding and support!
