### ISSUE TITLE
module 'ffmpeg' has no attribute 'Error'

### ISSUE THREAD

**Issue by richiec77** [Michele0303/TikTok-Live-Recorder#58]
I keep getting this issue when running the following command:

python3 main.py -user collectivespacesg -mode automatic -ffmpeg

Any ideas?
I have ffmpeg-python installed.

Requirement already satisfied: ffmpeg-python in /opt/homebrew/lib/python3.11/site-packages (0.2.0)
Requirement already satisfied: future in /opt/homebrew/lib/python3.11/site-packages (from ffmpeg-python) (0.18.3)

**Comment by Michele0303** [comment]
Launch this on cmd:
pip list | find "ffmpeg"

And uninstall all ffmpeg packages that are not
ffmpeg-python

**Comment by richiec77** [comment]
Ran it
richardcrossman@Richards-MacBook-Pro ~ % pip list | grep "ffmpeg"

ffmpeg             1.4
ffmpeg-python      0.2.0
richardcrossman@Richards-MacBook-Pro ~ % pip uninstall ffmpeg      
Found existing installation: ffmpeg 1.4
Uninstalling ffmpeg-1.4:
  Would remove:
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg-1.4.dist-info/*
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/*
  Would not remove (might be manually added):
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/_ffmpeg.py
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/_filters.py
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/_probe.py
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/_run.py
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/_utils.py
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/_view.py
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/dag.py
    /opt/homebrew/lib/python3.11/site-packages/ffmpeg/nodes.py
Proceed (Y/n)? y
  Successfully uninstalled ffmpeg-1.4

Still get the same error
[*] STARTED RECORDING... [PRESS 'q' TO STOP RECORDING]
module 'ffmpeg' has no attribute 'Error'

**Comment by richiec77** [comment]
Ok I removed all ffmpeg packages and did the pip install -r requirements.txt and this has fixed it!
Thanks
