### ISSUE TITLE
Hello, I have a question about automatic recording.

### ISSUE THREAD

**Issue by countdown88** [Michele0303/TikTok-Live-Recorder#6]
Hello, I have a question about automatic recording.
i made a .bat file and the contents are as follows.

cd C:\PROGRA~1\TikTok-Live-Recorder
python main.py -user userid -mode automatic

and I changed main.py 
 time.sleep(TIMEOUT * 60) => time.sleep(TIMEOUT * 12)
because, I want to check every minute ( 1 minute)

However, when the live streaming actually starts, it doesn't recognize it. 
If i run it after the live streaming starts, it works well.

Can you tell what the problem is?

**Comment by Michele0303** [comment]
I'll investigate and let you know

**Comment by spinningsand** [comment]
I was also having an issue with auto mode not recognizing when someone comes online.

**Comment by Michele0303** [comment]
Fixed
