### ISSUE TITLE
Ffmpeg is not installed error

### ISSUE THREAD

**Issue by mariogrc** [Michele0303/TikTok-Live-Recorder#60]
- Code used. Happens with any USER or ROOM_ID. Using Windows 11 and cmd:

`python main.py -user USER -mode automatic -ffmpeg`

- Output of the program
```
[*] USERNAME USER
[*] ROOM_ID ROOMID

[*] URL FLV https://pull-q5-sg01.tiktokcdn.com/stage/stream-ROOMID_or4.flv

[*] STARTED RECORDING... [PRESS 'q' TO STOP RECORDING]
[-] FFmpeg is not installed.
```

However when I run `pip install -r requirements.txt` it says
`Requirement already satisfied: ffmpeg-python in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (0.2.0)`

Manual mode without -ffmpeg works fine. But trying to convert it to mp4 at the end gives the same error.

**Comment by Michele0303** [comment]
Try:
https://github.com/Michele0303/TikTok-Live-Recorder/issues/58

**Comment by shadowdragon245** [comment]
i get this error #58 did not help

**Comment by shadowdragon245** [comment]
![image](https://github.com/Michele0303/tiktok-live-recorder/assets/102801794/0bff7261-def9-4e84-838d-c10971ccf580)

**Comment by Michele0303** [comment]
> ![image](https://user-images.githubusercontent.com/102801794/277506555-0bff7261-def9-4e84-838d-c10971ccf580.png)

Have you tried uninstalling and installing again?

**Comment by mariogrc** [comment]
In my case what solved the issue was going to https://www.ffmpeg.org/ and install ffmpeg from there. Idk what it is what I downloaded or if it's necessary but after that It worked

**Comment by shadowdragon245** [comment]
install what and where?

**Comment by Michele0303** [comment]
> install what and where? and yes have reinstalled it

Do not use the -ffmpeg flag

**Comment by shadowdragon245** [comment]
then i cant do auto?
