### ISSUE TITLE
Recording Restarts Frequently

### ISSUE THREAD

**Issue by Eikreis** [Michele0303/tiktok-live-recorder#62]
On version 3.9, command example:
py main.py -user username -mode automatic -ffmpeg

Recorder drops and restarts the recording multiple times during the stream, generated 10 files from
TK_username_2023.07.04_16-12-37 thru TK_username_2023.07.04_16-19-41

So 10 files over the span of about 7 minutes, that's a ton. I can't imagine what I'm going to get on long streams...

**Comment by roju** [comment]
Try my fork which has resolved this issue:
https://github.com/roju/tiktok-live-recorder

**Comment by spinningsand** [comment]
> Try my fork which can handle lagging and produce fewer video files: https://github.com/roju/tiktok-live-recorder

Works good so far. There was 1 streamer I couldn't record and it gave me this error:

` ERROR - rtmp_pull_url not in response: {'data': {'prompts': ''}, 'extra': {'now': 1692122709147}, 'status_code': 4003110}`

**Comment by Michele0303** [comment]
> Hey there, first off, huge thanks to the creator of this project. And shoutout to @roju for an awesome fork of it. I'm using the @roju version and recently I thought about setting up a dedicated folder for videos right at the root of the project. So, what I do is call the script using this command: `python ttlr.py -user username -ffmpeg -combine -out_dir video`. But here's where the issue pops up - during the concatenation step, it creates a txt file named concat.txt inside the video folder and that's when the script just crashes.

Please, for issues related to roju's fork, open an issues from him

**Comment by roju** [comment]
@Marksmanship256 Hi there, I didn’t realize issues weren’t enabled on my fork. Just enabled it. I’ll be monitoring and responding to the issues on my fork from now on.
