### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by huynhan1441** [Michele0303/TikTok-Live-Recorder#63]
I have runed python3 main.py -h but this show: 
Traceback (most recent call last):
  File "/Users/xxx/TikTok-Live-Recorder/main.py", line 4, in <module>
    from tiktokbot import TikTok
  File "/Users/xxx/TikTok-Live-Recorder/tiktokbot.py", line 2, in <module>
    import requests as req
ModuleNotFoundError: No module named 'requests'

Plz help me, I am non coder

**Comment by Michele0303** [comment]
pip install -r requirements.txt

**Comment by huynhan1441** [comment]
<img width="1546" alt="Screen Shot 2023-07-05 at 22 46 31" src="https://github.com/Michele0303/TikTok-Live-Recorder/assets/118896448/aa0dd84f-1a4a-468f-ba5b-5a008e6e72fb">

Hi i have installed Ffmpeg but this show " no module named ffmpeg ". Plz help me, thank u so much

**Comment by Michele0303** [comment]
pip install ffmpeg-python
