### ISSUE TITLE
Unable to find stream URL?

### ISSUE THREAD

**Issue by KevinDurantsBurner** [Michele0303/tiktok-live-recorder#64]
Does anyone know why some lives are unable to find stream url even though they are live? Typing room_id or username just goes straight to unable to find stream url

**Comment by CyberbobGR** [comment]
Yes, i have this problem too. Unfortunately there are no updates for a month now

**Comment by roju** [comment]
This happened to me when the stream was private or followers-only mode. Currently working on a solution to record private streams which requires logging in.

**Comment by KevinDurantsBurner** [comment]
Yeah it's weurd because for me i've tried recording a private profile just by pluggint in the username and it records completely fine and few non-private profiles have that stream url issue. Very odd

> This happened to me when the stream was private or followers-only mode. Currently working on a solution to record private streams which requires logging in.

**Comment by roju** [comment]
@KevinDurantsBurner Are you sure the profile was actually private? This is the response when I try to get the live url of a private account which is currently live:
```
{
    "data":
    {
        "message": "user is in blocklist",
        "prompts": "This account is private, follow the host to watch their broadcast"
    },
    "extra":
    {
        "now": 1689045524850
    },
    "status_code": 30006
}
```

**Comment by KevinDurantsBurner** [comment]
> @KevinDurantsBurner Are you sure the profile was actually private? This is the response when I try to get the live url of a private account which is currently live:
> 
> ```
> {
>     "data":
>     {
>         "message": "user is in blocklist",
>         "prompts": "This account is private, follow the host to watch their broadcast"
>     },
>     "extra":
>     {
>         "now": 1689045524850
>     },
>     "status_code": 30006
> }
> ```

Hmm yeah their profile was private as it also said followers only on their videos.

Maybe it's because i'm using an older version? I still use 2.8 as I found that to be the most reliable

**Comment by Michele0303** [comment]
> > @KevinDurantsBurner Are you sure the profile was actually private? This is the response when I try to get the live url of a private account which is currently live:
> > ```
> > {
> >     "data":
> >     {
> >         "message": "user is in blocklist",
> >         "prompts": "This account is private, follow the host to watch their broadcast"
> >     },
> >     "extra":
> >     {
> >         "now": 1689045524850
> >     },
> >     "status_code": 30006
> > }
> > ```
> 
> Hmm yeah their profile was private as it also said followers only on their videos.
> 
> Maybe it's because i'm using an older version? I still use 2.8 as I found that to be the most reliable

It is recommended to use the latest version. A check is now made to verify that the profile is not private
