### ISSUE TITLE
CMD windows closing on it's own

### ISSUE THREAD

**Issue by Sullyscharger** [Michele0303/TikTok-Live-Recorder#65]
Hi, so I've been using this program for a while and have set up .bat files to make it easier for me to record lives everything was going fine until recently, I found that the .bat windows would close after an amount of time which never happened before as I would be running the files overnight. Any one have any ideas? At first I thought that I may be running too many at a time so I reduced it to 5 windows but even still the issue persists. Any help would be much appreciated!

**Comment by Michele0303** [comment]
Try inserting

`pause`

At the end of your bat file, so it won't close when finished and you can understand the error, if any

**Comment by Sullyscharger** [comment]
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
'stream_url'
[-] Unable to find stream url.

is the error I get after a while

**Comment by Sullyscharger** [comment]
Ok seem to have found a work around, probably obvious but all i did was input :start then the script on the second line and on the third just made it loop back so "goto start"
