### ISSUE TITLE
Example of request

### ISSUE THREAD

**Issue by madigali** [Michele0303/TikTok-Live-Recorder#7]
Hi can you, give your example of request? Code is given this error unrecognized arguments: [-room_id 7200624350272899846] [-mode MODE]

**Comment by Michele0303** [comment]
https://www.tiktok.com/@tiktok

(manual mode)
python main.py -user tiktok
python main.py -room_id 7199101195288333102

(automatic mode)
python main.py -user tiktok -mode automatic
python main.py -room_id 7199101195288333102 -mode automatic
