### ISSUE TITLE
403 forbidden when trying to get room ID

### ISSUE THREAD

**Issue by rando-username** [Michele0303/tiktok-live-recorder#70]
Similar symptoms as https://github.com/Michele0303/tiktok-live-recorder/issues/37

Adding a `print(response)` after this line https://github.com/Michele0303/tiktok-live-recorder/blob/d1a043781e7ca5e16b49e7d417b53a56b89c78b1/tiktokbot.py#L234C14-L234C14 just says 403 forbidden

**Comment by bakuchanlove** [comment]
Also having same problem from few hours ago :(

**Comment by Michele0303** [comment]
You turned down the delay too much

**Comment by rando-username** [comment]
Sorry, what do you mean by delay? I don't see any setting pertaining to that. My only command used is 

```
python main.py -user <username> -mode automatic -ffmpeg
```

Also, this has persisted even after I stopped the command for more than a day. Do you have a remedy you can suggest @Michele0303 ?

**Comment by nicolas916** [comment]
Same, I am having this issue and am interested in knowing how to adjust this delay. The issue started happening in the middle of the day, without me changing anything.

**Comment by Michele0303** [comment]
Unfortunately tiktok after a while, it blocks your ip
