### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by broklin48** [Michele0303/tiktok-live-recorder#71]
I recently had a problem like this. What should i do?
![image](https://github.com/Michele0303/tiktok-live-recorder/assets/122853490/76dd57e2-0006-4e53-ace8-03918675fc2f)

**Comment by Michele0303** [comment]
Can I see which command you used?

**Comment by cj86gji4** [comment]
I have the same problem, use the command : main.py -url https://www.tiktok.com/@xxxxx/live
(xxxxx is user name.)
It seems that url parameters cannot be used...
