### ISSUE TITLE
Multiple lives

### ISSUE THREAD

**Issue by guitiba05** [Michele0303/tiktok-live-recorder#72]
It would be nice if there was a multiple live recorder, using a proxy system.

**Comment by Michele0303** [comment]
Open multiple tabs and use the -proxy option

**Comment by guitiba05** [comment]
is there a way to add multiple proxies to the same tab?

**Comment by Michele0303** [comment]
Unfortunately, you can't add multiple proxies to the same tab. No, I don't know where to find good proxies, sorry

**Comment by roju** [comment]
I have had success using TOR proxy
