### ISSUE TITLE
Can't get room_id without log in

### ISSUE THREAD

**Issue by lotaf99** [Michele0303/tiktok-live-recorder#73]
can't get room_id without login, if we type command with user parameter we can't get room_id

<img width="707" alt="Screenshot 2023-09-06 at 19 04 54" src="https://github.com/Michele0303/tiktok-live-recorder/assets/36005235/8ed05e10-78d0-432e-a295-1679b81f12be">

<img width="1029" alt="Screenshot 2023-09-06 at 19 05 10" src="https://github.com/Michele0303/tiktok-live-recorder/assets/36005235/fc1c821c-6240-4925-b2e8-4d1b95d099e4">

while we inspect element from tiktok.com/@(user)/live , we can see the room_id in <head> area
<img width="992" alt="Screenshot 2023-09-06 at 19 12 45" src="https://github.com/Michele0303/tiktok-live-recorder/assets/36005235/96054576-e267-4848-8dc9-bd32bb644142">

**Comment by 201610370311176** [comment]
yeah i have same problem too whilue using -user it failed to get the room_id but if we use the room id instead of user its work as usual

**Comment by jackingpanda** [comment]
my script is also like this, have been 2 days. 
trying to make a solving script with this too, but no luck.

```
        # Step 3: Cari room ID dalam tag <meta>
        soup = BeautifulSoup(response.text, 'html.parser')
        meta_tags = soup.find_all('meta', {'content': re.compile(r'snssdk1180://live\?room_id=\d+')})
        if meta_tags:
            room_id = re.search(r'room_id=(\d+)', meta_tags[0]['content']).group(1)
        else:
            logging.error(f"Tidak dapat menemukan room ID untuk @{username}. URL mungkin tidak valid.")
            print(f"Tidak dapat menemukan room ID untuk @{username}. URL mungkin tidak valid.")
            return
```

**Comment by lotaf99** [comment]
i don't now why that script didn't get meta tag, but now i use script from roja

https://github.com/roju/tiktok-live-recorder

that i can use paramater user with browser extension and resolve can't get room id without login

**Comment by qqqqqqq12158** [comment]
> 我現在不知道為什麼該腳本沒有獲得元標記，但現在我使用 roju 的腳本
> 
> https://github.com/roju/tiktok-live-recorder
> 
> 我可以使用帶有瀏覽器擴展的參數用戶並解決在沒有登錄的情況下無法獲取房間ID的問題

What methods can I use to obtain the room ID? Is the room ID fixed? Thank you very much for your response. I used the program you recommended, and it was working fine yesterday. However, I just noticed that an error occurred.
