### ISSUE TITLE
finish's randomly even though the live didn't stop

### ISSUE THREAD

**Issue by Geczy** [Michele0303/tiktok-live-recorder#74]
any idea what could cause this? 

<img width="853" alt="image" src="https://github.com/Michele0303/tiktok-live-recorder/assets/1036968/5c567d43-deb3-4bda-8cb8-6fcc75bd7aac">

**Comment by roju** [comment]
Might be because the stream lagged and you weren't using automatic mode. You could try [my fork](https://github.com/roju/tiktok-live-recorder) which is better at handling lag.

**Comment by Geczy** [comment]
Ohh nice I’ll try your fork tomorrow. Auto mode does look very useful for
me. Anything your fork could be missing from upstream? I see the fork is a
bit behind

**Comment by roju** [comment]
@Geczy Not really that I am aware of. Some minor stuff was removed intentionally though.
