### ISSUE TITLE
mode automatic

### ISSUE THREAD

**Issue by realfan2020collector** [Michele0303/TikTok-Live-Recorder#8]
Hello
It was successfully installed and successfully records live videos, but does not start recording in "automatic" mode.
I enter the command:
python main.py -user USERNAME -mode automatic
ENTER
and it gets stuck, it doesn't move on, it doesn't write anything, it just skips a line and that's it...
What could be the problem?
Can somebody help me?

Thank you!

**Comment by Michele0303** [comment]
Do you have the updated version?

**Comment by realfan2020collector** [comment]
I downloaded yesterday.
I don't find any version number, but I downloaded the latest version + update the python version too
btw, Where can I check the version numbers...?
Thank you

**Comment by Michele0303** [comment]
https://github.com/Michele0303/TikTok-Live-Recorder/releases/tag/2.0

**Comment by realfan2020collector** [comment]
Hello
I updated and run the command from cmd, now its works fine....
btw... now some room has youtube-dl error
![image](https://user-images.githubusercontent.com/125803173/220306406-fce52d00-1277-4b0f-a8cd-3a0d198ad24b.png)
I updated the latest version

**Comment by Michele0303** [comment]
the room id changes in each live. Make sure you always use the new one
