### ISSUE TITLE
Run in background/phone off

### ISSUE THREAD

**Issue by Eapeeex** [Michele0303/tiktok-live-recorder#80]
If I am using the code on android is there a way to have the code running with the phone is off? If not is there at least a way to have it run while the app is in the background?

**Comment by hakiminaim** [comment]
How you can get it to work? I got this error when I used room_id:

[*] 2023-10-16 15:12:32 - ERROR - 'stream_url'
[*] 2023-10-16 15:12:32 - ERROR - Exception caught in main:
[-] Unable to find stream url.

I also got this error when I used URL:

 [*] 2023-10-16 15:25:31 - ERROR - list index out of range


  _____ _ _   _____    _     _    _           ___                   _
 |_   _(_) |_|_   _|__| |__ | |  (_)_ _____  | _ \___ __ ___ _ _ __| |___ _ _
   | | | | / / | |/ _ \ / / | |__| \ V / -_) |   / -_) _/ _ \ '_/ _` / -_) '_|
   |_| |_|_\_\ |_|\___/_\_\ |____|_|\_/\___| |_|_\___\__\___/_| \__,_\___|_|

   V4.1

^C
[1]+  Exit 1                  python main.py -url https://www.tiktok.com/@***/live?enter_method=others_photo

**Comment by Michele0303** [comment]
When the phone is off, no. When the app is in the background, however, yes.

**Comment by Naderrnawar** [comment]
Anyway t

> When the phone is off, no. When the app is in the background, however, yes.


Anyway to make it working when phone off? Forced program or code?

**Comment by elbarbudo** [comment]
I have a similar issue on Linux debian.
Launching from an active window, and latteing it open works fine.

Putting in background it stops working after a certain time.

**Comment by Michele0303** [comment]
> Anyway t
> 
> > When the phone is off, no. When the app is in the background, however, yes.
> 
> Anyway to make it working when phone off? Forced program or code?

You should have the tool on a server
