### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by hakiminaim** [Michele0303/tiktok-live-recorder#81]
How you can get it to work? I got this error when I used room_id:

[] 2023-10-16 15:12:32 - ERROR - 'stream_url'
[] 2023-10-16 15:12:32 - ERROR - Exception caught in main:
[-] Unable to find stream url.

I also got this error when I used URL:

[*] 2023-10-16 15:25:31 - ERROR - list index out of range

|_ () || || | | | ()_ _____ | _ ___ __ ___ _ _ | |_ _ _
| | | | / / | |/ _ \ / / | || \ V / -) | / -) / _ \ '/ ` / -) '|
|| ||_\ |_|_/_\ |||_/___| ||____/| _,___||

V4.1

^C
[1]+ Exit 1 python main.py -url https://www.tiktok.com/@***/live?enter_method=others_photo

**Comment by eliich** [comment]
blacklisted IP in certain countries :/. i would try a VPN/proxy. VPN/PROXY is only for requests. but actual download is through your IP. which isnt an issue as ive ran like 4 from one single IP
