### ISSUE TITLE
Unable to Find room_id. I'll try again in 2 minutes

### ISSUE THREAD

**Issue by yw-tsikin** [Michele0303/tiktok-live-recorder#82]
I followed the steps to install, all the requirements are installed properly yet that error shows up. Both on Android and using Desktop PC.
![image](https://github.com/Michele0303/tiktok-live-recorder/assets/78951828/0cb3f546-2a9f-4091-9813-d50ad3846e0f)

**Comment by aibi786** [comment]
getting the same error
did u found any solution or alternative?
plz do share

**Comment by mahmoudossama1** [comment]
Same problem anything yet for this problem ?

**Comment by Michele0303** [comment]
try the new version
