### ISSUE TITLE
How to make duration longer

### ISSUE THREAD

**Issue by sfdfgvdvdsvb** [Michele0303/tiktok-live-recorder#83]

**Comment by sfdfgvdvdsvb** [comment]
ik the python main.py - duration but whats the prefix for the numbers and shit?

**Comment by Michele0303** [comment]
What? Use:
```
-duration seconds
```
```
-duration 3600
```

**Comment by sfdfgvdvdsvb** [comment]
another question it randomly stops and says stream lagging but does it constly and created like 30 dif recording how do i fix that?

**Comment by Michele0303** [comment]
Unfortunately, it happens when the host lags

**Comment by yah00078** [comment]
I think it could be a good idea for exemple to tag on filename the file part number.
For example:  TK_Livename_Date_01, don't really know if tiktok give us live duration, but if, while duration is upper than last in memory on file creation, add a part ?

**Comment by Michele0303** [comment]
> I think it could be a good idea for exemple to tag on filename the file part number. For example: TK_Livename_Date_01, don't really know if tiktok give us live duration, but if, while duration is upper than last in memory on file creation, add a part ?

Sorry I don't think I understand
