### ISSUE TITLE
Unable to find stream url

### ISSUE THREAD

**Issue by CodeChrist** [Michele0303/tiktok-live-recorder#84]
Not sure if tiktok recently changed something but im unable to find the following users stream url, even though it worked before. Thanks for the great project though :)

[*] USERNAME ex_muslim1
[*] ROOM_ID 7296778753898760993

[*]  - ERROR - 'stream_url'
[*] - ERROR - Exception caught in main:
[-] Unable to find stream url.

Version: 4.1

**Comment by yah00078** [comment]
I have the same issue on some stream like aswar_play , but other seems ok for the moment

**Comment by Michele0303** [comment]
try new version
