### ISSUE TITLE
Record subscriber-only streams?

### ISSUE THREAD

**Issue by cstoraker** [Michele0303/tiktok-live-recorder#87]
Is there a way to 'log-in' to Tiktok in order to record subscriber only lives?

**Comment by Michele0303** [comment]
Currently no

**Comment by nlienard** [comment]
is it plan to do it ?

**Comment by Michele0303** [comment]
It's now a feature:

https://github.com/Michele0303/tiktok-live-recorder/blob/main/GUIDE.md#how-to-set-cookies
