### ISSUE TITLE
How can I make it send videos to the telegram channel?

### ISSUE THREAD

**Issue by Enigma-tht** [Michele0303/tiktok-live-recorder#88]
How can I make it send videos to the telegram channel? Will there be an update regarding this?

**Comment by sotero1113** [comment]
Look at telegram API documents and look into how you can post to telegram then add that logic to the script once your video finishes recording.

**Comment by Enigma-tht** [comment]
I've done what you said before, but the video length can only be up to 1 minute. Telegram API blocks videos longer than 1 minute. Is there a way to bypass this limitation? Or do you have any other platform suggestions that don't restrict video sending?

**Comment by sotero1113** [comment]
> elegram API

I think it can allow videos longer then 1 minute but it has a file size restriction of 50mb. you can upload the video to google cloud storage or aws s3 and then just send the url link to your telegram channel

**Comment by Michele0303** [comment]
I added it to the todo list
