### ISSUE TITLE
Captcha required ? - on non blacklisted Country [GER]

### ISSUE THREAD

**Issue by fellow88** [Michele0303/tiktok-live-recorder#89]
main.py -user XXX -mode automatic -output F:\+tiktok -ffmpeg

V4.1

[*] 2023-12-15 17:15:50 - ERROR - Exception caught in main:
[-] Captcha require or country blocked. Use a vpn or room_id.
[-] How to get room id: https://github.com/Michele0303/TikTok-Live-Recorder/blob/main/GUIDE.md#how-to-get-room_id
[-] Unrestricted country list: https://github.com/Michele0303/TikTok-Live-Recorder/edit/main/GUIDE.md#unrestricted-country

Just Manual Mode with room_id works.

This Problem started today,

everyhing worked flawless until now on automatic mode for month.

**Comment by elbarbudo** [comment]
Same thing for me in France.
Apparently, TikTok made some changes.

More : on a active live, in manual mode, I got "user is offline" (either with -user or room_number)

**Comment by elbarbudo** [comment]
ERRATA : at 22:32:47 everything seems to be working again

**Comment by fellow88** [comment]
Same here, seems to work again

**Comment by fellow88** [comment]
-
