### ISSUE TITLE
How to use --autoconvert

### ISSUE THREAD

**Issue by elbarbudo** [Michele0303/tiktok-live-recorder#92]
When I try 

python3 main.py main.py --autoconvert 

I just get 
main.py: error: unrecognized arguments: main.py --autoconvert

What is the use of this flag, how to use it?

**Comment by Lejoumou** [comment]
Hi 
Try  --auto-convert 
but
python -main.py -h is your best friend for verify syntax ;)

**Comment by Michele0303** [comment]
No longer supported, now conversion is always automatic
