### ISSUE TITLE
Change the frequency of automatic recordings 

### ISSUE THREAD

**Issue by Necrow51** [Michele0303/tiktok-live-recorder#93]
Hi, The frequency of automatic recordings is set to 5 minutes by default, is it possible to change the value?

**Comment by Rustbeard86** [comment]
I realize this is an old question, but here is the answer.
`tiktok-live-recorder\src\utils\enums.py` -> That file has the logic you want.

`class TimeOut(IntEnum):
    """ 
    Enumeration that defines timeout values. 
    """

    def __mul__(self, operator):
        return self.value * operator

    ONE_MINUTE = 60
    AUTOMATIC_MODE = 5
    CONNECTION_CLOSED = 2`

`    AUTOMATIC_MODE = 1`

Or something similar.
