### ISSUE TITLE
Unable to find stream url

### ISSUE THREAD

**Issue by elbarbudo** [Michele0303/tiktok-live-recorder#97]
Suddently, (today at about 22h french time) I got :

`
[*] 2024-01-01 22:37:17 - INFO - USERNAME: gulmensali
[*] 2024-01-01 22:37:17 - INFO - ROOM_ID:  7319241713460939552
[*] 2024-01-01 22:37:19 - ERROR - 'stream_url'
[*] 2024-01-01 22:37:19 - ERROR - Exception caught in main:
[-] Unable to find stream url.
`
Did TikTok change something?
It was running smoothly since several days.

**Comment by MexTrx** [comment]
Looks like the person made the acct private.

**Comment by Reiszecke** [comment]
To add to this, this happens on publicly available accounts too.

**Comment by Michele0303** [comment]
Add cookies 

https://github.com/Michele0303/tiktok-live-recorder/blob/main/GUIDE.md#how-to-set-cookies
