### ISSUE TITLE
ERROR - FFmpeg is not installed

### ISSUE THREAD

**Issue by Audiojungle** [Michele0303/tiktok-live-recorder#98]
i get this error when i record more than 2 lives

**Comment by Audiojungle** [comment]
but ffmpeg is installed well and last version

**Comment by Audiojungle** [comment]
actually it's pretty random, somtimes shows this error when i record a second live other times when i record a third one.... sometimes shows this error for one special user

**Comment by Audiojungle** [comment]
yeah i'm limited to record two lives, don't get why

**Comment by kamalls** [comment]
pip install ffmpeg
pip3 install ffmpeg

**Comment by cruizerway** [comment]
i try install ffmpeg

**Comment by kamalls** [comment]
uninstall your curent python and try install python 3.10

**Comment by PaulJavey** [comment]
I tried it on 2 computers and 3 different version of python 3.9, 3.10, 3.11 and have the same issues. It didn't worked for a single live

**Comment by PaulJavey** [comment]
You have to use a different type of url like this : https://www.tiktok.com/xxxxxxx/live?enter_from_merge=others_homepage&enter_method=others_photo

**Comment by Michele0303** [comment]
Fixed in version 5.4
