### ISSUE TITLE
 Change in the specifications of TikTok Live

### ISSUE THREAD

**Issue by Green65** [Michele0303/tiktok-live-recorder#99]
It seems there has been a change in the specifications of TikTok Live, and I'm wondering if this app is still usable? I was originally using a different app, but it became unusable, so I'm looking for an alternative.

**Comment by Michele0303** [comment]
I investigate and resolve eventually

**Comment by Reiszecke** [comment]
With the PR at https://github.com/Michele0303/tiktok-live-recorder/pull/102 some lives work, other don't with `Unable to find stream url.`
